name: Debug CI

on:
  push:
    branches: [main]

jobs:
  debug:
    name: Debug Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Show environment info
        run: |
          node --version
          npm --version
          pwd
          ls -la

      - name: Check package files
        run: |
          echo "=== package.json ==="
          head -20 package.json
          echo "=== package-lock.json exists ==="
          ls -la package*.json

      - name: Try npm install
        run: |
          npm install || npm install --legacy-peer-deps
          echo "Dependencies installed successfully"

      - name: Run tests
        run: |
          npm test
          echo "Tests completed successfully"

      - name: Run lint
        run: |
          npm run lint
          echo "Linting completed successfully"